spring:
  application:
    name: limits-service

  config:
    import: optional:configserver:http://localhost:8888

  profile:
    active: qa

  cloud:
    config:
      profile: dev
      
server:
  port: 8900

limits-service:
  minimum: 7
  maximum: 70